POST http://localhost:8080/api/chat HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "conversationId": "1447eadc-6c64-481b-aee3-b90ab5c1ef2f",
    "message": "Ich suche Immobilien in Berlin"
}
